Repository reignkk1/tutoring-client, pull requests merged in 2023-05, with the labels that each got.

#31 style: Write Editor
  package-lock.json
  package.json
  src/App.tsx
  src/components/write/Editor.tsx
  src/pages/FindPage.tsx
  src/pages/Notice.tsx
  src/pages/Write.tsx
  src/styles/GlobalStyles.tsx
Labels: 🧑‍🎨 Style

#33 [#32] styled-components 버전 에러 해결
  package-lock.json
  package.json
  src/components/common/Wrapper.tsx
  src/components/detail/SCategory.tsx
  src/components/detail/TCategory.tsx
  src/components/mypage/Category.tsx
  src/components/postPage/Button.tsx
  src/components/postPage/PostBox.tsx
  src/components/postPage/SearchBar.tsx
  src/components/postPage/TitleBox.tsx
  src/pages/FindPage.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/Notice.tsx
  src/pages/StudentDetail.tsx
  src/pages/TeacherDetail.tsx
  src/pages/Write.tsx
  src/styles/Form.tsx
Labels: 🐞 Bug

#36 feat: 글쓰기 Select 추가
  src/components/write/Editor.tsx
  src/pages/Write.tsx
Labels: ✨ Feature, 🧑‍🎨 Style

#37 유효성 검사, 이메일 인증 추가
  package-lock.json
  package.json
  src/hooks/useForm.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: ✨ Feature

#40 Feat/refact sign
  src/api/auth.ts
  src/hooks/useForm.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/styles/Form.tsx
Labels: ✨ Feature, 🔨 Refactor

#41 feat: 글 작성 Selector 추가
  package-lock.json
  package.json
  src/App.tsx
  src/UserData.ts
  src/components/layout/Header.tsx
  src/components/write/AddressSearch.tsx
  src/components/write/Editor.tsx
  src/components/write/Selector.tsx
  src/pages/Write.tsx
Labels: ✨ Feature, 🧑‍🎨 Style

#43 feat: 서버 이메일 인증, 사용자 정보 추가
  src/api/auth.ts
  src/hooks/useForm.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/styles/Form.tsx
  src/util/authRegex.ts
Labels: ✨ Feature, 🧑‍🎨 Style

#45 refactor: 셀렉터 항목
  src/components/write/DesitredSubjectsList.tsx
  src/components/write/Editor.tsx
  src/components/write/Selector.tsx
  src/pages/Write.tsx
Labels: 🔨 Refactor

#47 Refac/form 폼 리팩토링 및 회원가입 백엔드 요청 구현
  src/App.tsx
  src/api/auth.ts
  src/components/sign/InputField.tsx
  src/hooks/useForm.tsx
  src/hooks/useSign.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/styles/Form.tsx
  src/util/authRegex.ts
  src/util/sign/formConfig.tsx
  src/util/sign/validationRules.ts
Labels: ✨ Feature, 🔨 Refactor
