Repository reignkk1/tutoring-client, pull requests merged in 2023-06, with the labels that each got.

#52 feat: 게시글 작성, 불러오기 API 작업
  src/api/Post.ts
  src/components/postPage/PostBox.tsx
  src/components/write/DesitredSubjectsList.tsx
  src/components/write/SelectData.ts
  src/components/write/Selector.tsx
  src/pages/FindPage.tsx
  src/pages/Notice.tsx
  src/pages/Write.tsx
Labels: ✨ Feature, 🔨 Refactor

#54 refactor: 게시글 상세보기 페이지 작업
  src/App.tsx
  src/api/Post.ts
  src/components/postPage/PostBox.tsx
  src/pages/FindPage.tsx
  src/pages/MyPage.tsx
  src/pages/PostDetail.tsx
  src/pages/StudentDetail.tsx
  src/pages/TeacherDetail.tsx
  src/pages/Write.tsx
Labels: 🔨 Refactor

#56 feat: 공지사항, 학생 게시물 API 작업
  src/App.tsx
  src/api/Post.ts
  src/components/postPage/FindPostList.tsx
  src/components/postPage/NoticePostList.tsx
  src/components/postPage/PostList.tsx
  src/components/write/Editor.tsx
  src/pages/FindPage.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.tsx
  src/pages/NoticeWrite.tsx
  src/pages/PostDetail.tsx
  src/pages/Write.tsx
Labels: 🐞 Bug, ✨ Feature

#59 feat: 로그인 관련 작업했습니다
  src/App.tsx
  src/api/auth.ts
  src/components/layout/Header.tsx
  src/components/mypage/PostList.tsx
  src/context/AuthContext.tsx
  src/pages/Logout.tsx
  src/pages/MyPage.tsx
  src/pages/RootLayout.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Write.tsx
  src/util/format.ts
  src/util/sign/auth.ts
  src/util/sign/formConfig.tsx
Labels: ✨ Feature

#63 feat: 유저 페이지 작업
  src/App.tsx
  src/api/Post.ts
  src/api/auth.ts
  src/assets/noImg.png
  src/pages/PostDetail.tsx
  src/pages/UserPage.tsx
Labels: ✨ Feature

#66 Style/전체적인 스타일링 변경
  package-lock.json
  package.json
  src/App.tsx
  src/api/note.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/postPage/Button.tsx
  src/components/postPage/SearchBar.tsx
  src/fonts.d.ts
  src/pages/FindPage.tsx
  src/pages/Home.tsx
  src/pages/Notes.tsx
  src/pages/PostDetail.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature, 🧑‍🎨 Style

#69 feat/style: 쪽지함 화면 작업 및 게시물 찾기, 로그인 스타일링
  src/api/note.ts
  src/components/common/Wrapper.tsx
  src/components/layout/Header.tsx
  src/components/notes/Category.tsx
  src/components/postPage/FindPostList.tsx
  src/components/postPage/SearchBar.tsx
  src/components/postPage/TitleBox.tsx
  src/pages/FindPage.tsx
  src/pages/MyPage.tsx
  src/pages/Notes.tsx
  src/pages/PostDetail.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/UserPage.tsx
  src/pages/Write.tsx
  src/styles/Form.tsx
  src/styles/GlobalStyles.tsx
  src/util/format.ts
  src/util/sign/formConfig.tsx
Labels: ✨ Feature, 🧑‍🎨 Style

#70 feat: 쪽지 보내기 기능
  src/api/Post.ts
  src/api/auth.ts
  src/api/note.ts
  src/components/common/Modal.tsx
  src/components/detail/MessageSendBox.tsx
  src/components/postPage/FindPostList.tsx
  src/components/write/AddressSearch.tsx
  src/pages/FindPageEdit.tsx
  src/pages/NoticeEdit.tsx
  src/pages/PostDetail.tsx
  src/pages/Write.tsx
Labels: ✨ Feature

#71 feat/style/refactor 쪽지, 전체 스타일링 및 수정
  public/favicon.ico
  public/index.html
  src/App.tsx
  src/api/Post.ts
  src/api/auth.ts
  src/api/note.ts
  src/components/detail/MessageSendBox.tsx
  src/components/layout/Header.tsx
  src/components/mypage/PostList.tsx
  src/components/postPage/FindPostList.tsx
  src/components/postPage/SearchBar.tsx
  src/components/write/Selector.tsx
  src/pages/FindPage.tsx
  src/pages/FindPageEdit.tsx
  src/pages/FindPwd.tsx
  src/pages/MyPage.tsx
  src/pages/Notes.tsx
  src/pages/PostDetail.tsx
  src/pages/UserPage.tsx
  src/pages/Write.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature, 🔨 Refactor, 🧑‍🎨 Style

#74 feat & refactor: 검색 기능 추가, 리덕스 도입
  src/App.tsx
  src/api/Post.ts
  src/api/note.ts
  src/components/common/Modal.tsx
  src/components/detail/MessageSendBox.tsx
  src/components/postPage/FindPostList.tsx
  src/components/postPage/NoticePostList.tsx
  src/components/postPage/SearchBar.tsx
  src/components/write/AddressSearch.tsx
  src/components/write/DesitredSubjectsList.tsx
  src/components/write/Editor.tsx
  src/components/write/Selector.tsx
  src/pages/FindPage.tsx
  src/pages/FindPageEdit.tsx
  src/pages/Notice.tsx
  src/pages/NoticeEdit.tsx
  src/pages/NoticeWrite.tsx
  src/pages/PostDetail.tsx
  src/pages/Write.tsx
  src/reducers/edit.ts
  src/reducers/modal.ts
  src/reducers/post.ts
  src/reducers/rootReducer.ts
  src/reducers/write.ts
Labels: ✨ Feature, 🔨 Refactor

#77 refactor: 전체적인 코드 리팩토링
  src/UserData.ts
  src/api/Post.ts
  src/api/auth.ts
  src/components/common/Button.tsx
  src/components/common/Modal.tsx
  src/components/postPage/FindPostList.tsx
  src/components/postPage/SearchBar.tsx
  src/components/write/AddressSearch.tsx
  src/components/write/DesitredSubjectsList.tsx
  src/components/write/Editor.tsx
  src/components/write/UserInfo.tsx
  src/components/write/WriteEditFormList.tsx
  src/hooks/useModal.tsx
  src/hooks/usePost.tsx
  src/hooks/useWriteEditForm.tsx
  src/pages/FindPage.tsx
  src/pages/FindPageEdit.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.tsx
  src/pages/NoticeEdit.tsx
  src/pages/NoticeWrite.tsx
  src/pages/PostDetail.tsx
  src/pages/Write.tsx
  src/reducers/rootReducer.ts
  src/reducers/write.ts
  src/reducers/writeEdit.ts
  src/types/category.ts
  src/util/format.ts
Labels: 🔨 Refactor

#78 fix&refactor: 메세지 답장 시 마지막 사람에게 보내지는 버그 수정 및 리덕스 툴킷으로 리팩토링중
  package-lock.json
  package.json
  public/index.html
  src/api/auth.ts
  src/api/note.ts
  src/components/common/Modal.tsx
  src/components/detail/MessageSendBox.tsx
  src/components/mypage/MessageSendBox.tsx
  src/components/notes/MessageSendBox.tsx
  src/components/notes/Note.tsx
  src/components/write/AddressSearch.tsx
  src/components/write/DesitredSubjectsList.tsx
  src/components/write/WriteEditFormList.tsx
  src/hooks/useModal.tsx
  src/hooks/usePost.tsx
  src/hooks/useWriteEditForm.tsx
  src/index.tsx
  src/pages/FindPage.tsx
  src/pages/FindPageEdit.tsx
  src/pages/Notes.tsx
  src/pages/Notice.tsx
  src/pages/PostDetail.tsx
  src/pages/UserPage.tsx
  src/pages/Write.tsx
  src/reduxHooks.ts
  src/store/configureStore.ts
  src/store/editPost.ts
  src/store/modal.ts
  src/store/post.ts
Labels: 🐞 Bug, 🔨 Refactor

#80 Refactor & Feat : 리덕스 툴킷 도입, 관리자 권한
  src/App.tsx
  src/api/Post.ts
  src/api/note.ts
  src/components/common/Modal.tsx
  src/components/notes/MessageSendBox.tsx
  src/components/postPage/SearchBar.tsx
  src/components/write/AddressSearch.tsx
  src/components/write/DesitredSubjectsList.tsx
  src/components/write/Editor.tsx
  src/components/write/UserInfo.tsx
  src/components/write/WriteEditFormList.tsx
  src/hooks/useIsAdmin.tsx
  src/hooks/useModal.tsx
  src/hooks/usePost.tsx
  src/hooks/useWriteEditForm.tsx
  src/pages/FindPage.tsx
  src/pages/FindPageEdit.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.tsx
  src/pages/NoticeEdit.tsx
  src/pages/NoticeWrite.tsx
  src/pages/PostDetail.tsx
  src/pages/UserPage.tsx
  src/reducers/modal.ts
  src/reducers/post.ts
  src/reducers/rootReducer.ts
  src/reducers/writeEdit.ts
  src/store/configureStore.ts
  src/store/editPost.ts
  src/store/modal.ts
  src/store/post.ts
Labels: ✨ Feature, 🔨 Refactor

#81 feat&fix: 카카오 로그인 구현 및 로그인 하지 않은 경우에도 상세보기 가능하도록 수정
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/api/auth.ts
  src/components/notes/Note.tsx
  src/components/sign/SocialKakao.tsx
  src/components/write/WriteEditFormList.tsx
  src/context/AuthContext.tsx
  src/hooks/usePost.tsx
  src/hooks/useWriteEditForm.tsx
  src/pages/MyPage.tsx
  src/pages/PostDetail.tsx
  src/pages/ProfileUpdate.tsx
  src/pages/SignIn.tsx
  src/styles/Form.tsx
  src/util/sign/formConfig.tsx
Labels: 🐞 Bug, ✨ Feature

#82 refactor&fix: api 호출하는 커스텀 리덕스 미들웨어 구현 및 자동 로그아웃 버그 해결
  src/App.tsx
  src/api/auth.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/notes/MessageSendBox.tsx
  src/components/notes/Note.tsx
  src/hooks/useNote.tsx
  src/pages/Home.tsx
  src/pages/Logout.tsx
  src/pages/Notes.tsx
  src/pages/RootLayout.tsx
  src/store/api.ts
  src/store/configureStore.ts
  src/store/middleware/api.ts
  src/store/middleware/error.ts
  src/store/middleware/log.ts
  src/store/note.ts
Labels: 🐞 Bug, 🔨 Refactor

#84 Feat: 글 작성 글자 수 제한 & 페이징
  src/api/Post.ts
  src/components/postPage/FindPostList.tsx
  src/components/postPage/NoticePostList.tsx
  src/components/write/WriteEditFormList.tsx
  src/pages/FindPage.tsx
  src/pages/FindPageEdit.tsx
  src/pages/PostDetail.tsx
  src/pages/Write.tsx
  src/store/post.ts
Labels: ✨ Feature

#85 style: 전체적으로 반응형 구현
  src/api/auth.ts
  src/components/layout/Header.tsx
  src/components/mypage/PostList.tsx
  src/components/notes/MessageSendBox.tsx
  src/components/postPage/FindPostList.tsx
  src/components/sign/SocialKakao.tsx
  src/components/write/UserInfo.tsx
  src/components/write/WriteEditFormList.tsx
  src/pages/FindPage.tsx
  src/pages/Home.tsx
  src/pages/Notes.tsx
  src/pages/SignIn.tsx
  src/pages/UserPage.tsx
  src/pages/Write.tsx
  src/styles/Form.tsx
  src/styles/GlobalStyles.tsx
Labels: 🧑‍🎨 Style

#87 delivery&style: aws배포 및 반응형 수정
  package.json
  src/api/Post.ts
  src/api/auth.ts
  src/api/note.ts
  src/components/common/Button.tsx
  src/components/layout/Footer.tsx
  src/components/notes/MessageSendBox.tsx
  src/components/postPage/NoticePostList.tsx
  src/components/postPage/SearchBar.tsx
  src/components/sign/SocialKakao.tsx
  src/pages/FindPage.tsx
  src/pages/FindPageEdit.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/Notes.tsx
  src/pages/Notice.tsx
  src/pages/PostDetail.tsx
  src/pages/UserPage.tsx
  src/pages/Write.tsx
  src/store/middleware/api.ts
  src/styles/GlobalStyles.tsx
Labels: 🎁 Delivery, 🧑‍🎨 Style

#90 refactor: post redux thunk 리팩토링 및 로딩 스피너 추가
  src/App.tsx
  src/api/auth.ts
  src/components/common/Button.tsx
  src/components/common/Loading.tsx
  src/components/layout/Header.tsx
  src/components/notes/Category.tsx
  src/components/post/FindPostList.tsx
  src/components/post/NoticePostList.tsx
  src/components/post/SearchBar.tsx
  src/components/post/TopSheet.tsx
  src/components/write/WriteEditFormList.tsx
  src/pages/FindPageEdit.tsx
  src/pages/Notes.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.tsx
  src/pages/NoticeEdit.tsx
  src/pages/NoticeWrite.tsx
  src/pages/PostDetail.tsx
  src/pages/Students.tsx
  src/pages/Teachers.tsx
  src/pages/Write.tsx
  src/store/category.ts
  src/store/configureStore.ts
  src/store/post/api/PostCreateThunk.ts
  src/store/post/api/PostDeleteThunk.ts
  src/store/post/api/PostReadThunk.ts
  src/store/post/api/PostUpdateThunk.ts
  src/store/post/post.ts
  src/store/post/postApiAction.ts
  src/store/post/postSlice.ts
  src/types/category.ts
Labels: ✨ Feature, 🔨 Refactor
