Repository reignkk1/tutoring-client, pull requests merged in 2023-07, with the labels that each got.

#91 refactor: 회원가입, 로그인 폼 리팩토링
  src/App.tsx
  src/api/auth.ts
  src/api/note.ts
  src/components/common/Button.tsx
  src/components/common/Loading.tsx
  src/components/layout/Header.tsx
  src/components/mypage/PostList.tsx
  src/components/notes/MessageSendBox.tsx
  src/components/notes/Note.tsx
  src/components/post/FindPostList.tsx
  src/components/post/SearchBar.tsx
  src/components/sign/FormInput.tsx
  src/components/sign/InputField.tsx
  src/components/sign/RadioInput.tsx
  src/components/sign/Select.tsx
  src/hooks/useSign.tsx
  src/pages/FindPwd.tsx
  src/pages/MyPage.tsx
  src/pages/Notes.tsx
  src/pages/PostDetail.tsx
  src/pages/ProfileUpdate.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/UserPage.tsx
  src/store/note.ts
  src/styles/Form.tsx
  src/styles/GlobalStyles.tsx
  src/util/sign/formConfig.tsx
  src/util/sign/validationRules.ts
Labels: 🔨 Refactor

#94 fix: 테스트 후 버그 해결
  src/App.tsx
  src/api/auth.ts
  src/components/notes/Note.tsx
  src/components/sign/FormInput.tsx
  src/components/sign/RadioInput.tsx
  src/components/sign/Select.tsx
  src/components/sign/SocialKakao.tsx
  src/hooks/useAuth.tsx
  src/pages/FindPwd.tsx
  src/pages/Notes.tsx
  src/pages/ProfileUpdate.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/store/auth.ts
  src/store/configureStore.ts
  tsconfig.json
Labels: 🐞 Bug, 🔨 Refactor

#95 fix & refactor: 발견된 버그 고침 & 리팩토링
  src/components/layout/Header.tsx
  src/components/notes/Note.tsx
  src/components/post/FindPostList.tsx
  src/components/post/SearchBar.tsx
  src/hooks/usePostScrollPage.tsx
  src/pages/Notes.tsx
  src/pages/Students.tsx
  src/pages/Teachers.tsx
  src/store/configureStore.ts
  src/store/middleware/api.ts
  src/store/post/pageSlice.ts
  src/util/sign/auth.ts
Labels: 🐞 Bug, 🔨 Refactor

#97 refactor: 카카오 로그인 사용자 추가정보 받기 리팩토링
  src/api/auth.ts
  src/pages/PostDetail.tsx
  src/pages/ProfileUpdate.tsx
  src/pages/UserPage.tsx
  src/pages/Write.tsx
  src/styles/Form.tsx
Labels: 🔨 Refactor

#98 fix: 카카오 로그인 프로필 업데이트 버그 수정
  src/api/auth.ts
  src/pages/MyPage.tsx
  src/pages/PostDetail.tsx
  src/pages/ProfileUpdate.tsx
  src/pages/UserPage.tsx
  src/pages/Write.tsx
Labels: 🐞 Bug
